# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Juarez Barbosa Junior
title: Azure Developer Engagement Lead - Microsoft
email: juarez.barbosa@gmail.com
website: https://juarezjunior.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: juarezjunior
linkedin_username: jujunior
github_username:  juarezjuniorgithub
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: juarez8junior8
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: JuarezJuniorComputing
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Sessionize
  icon: fas fa-globe
  url: https://sessionize.com/juarezjunior
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I’m Juarez Junior, Azure Developer Engagement Lead at Microsoft. Previously, a Principal Developer Advocate - Blockchain at Oracle and, Thought Leader and Technical Evangelist at IBM.

  My current interests are: Blockchain, IoT, Hyperledger, Ethereum, Corda, Rust, Kotlin, Java, Go, Solidity, Python, Cloud, DevOps, Docker, Kubernetes, Mobile, AI, SolutionsArchitecture, SoftwareArchitecture, Startups, Emerging Technologies.

content:
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        link: www.microsoft.com
        # link_text: boringcompany.com
        sub_title: Azure Developer Engagement Lead
        caption: July 2010 - Present
        quote: >
          https://developer.microsoft.com/en-ie/
        description: | # this will include new lines to allow paragraphs
            Developer Engagement and Relations Lead. I oversee all the developer outreach activities including developer marketing programs, customer and social media interactions, online and in-person events like webinars, technical workshops, conferences, hackathons, training and certification events, and local meetups, technical content creation and curation (articles and blog posts), implementation of code samples and technical guides as well as events organization and promotion.

  #- title: Education # Title for the section
    #layout: list # Type of content section (list/text)
    #content:
      #- layout: left
      #  title: Harvard University
      #  caption: 2010 - 2013
      #  sub_title: BSc Computer Science
      #  quote: >
      #    Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
      #  description: | # this will include new lines to allow paragraphs
      #    During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

      #    I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
    
  - title: Highlights
    layout: text
    content: | # this will include new lines to allow paragraphs
      Awards, technical certifications, diplomas and courses:
      - [IBM Mobile Thought Leader and Technical Evangelist](https://www.flickr.com/photos/15201803@N00/albums/72157697188449462)
      - [IBM Redbooks Author - Securing Your Mobile Business with IBM Worklight](https://play.google.com/store/books/details/Securing_Your_Mobile_Business_with_IBM_Worklight?id=qXvJAgAAQBAJ&gl=US)   
            
  
  - title: Talks
    layout: text
    content: | # this will include new lines to allow paragraphs
      Developer and customer engagement talks:
      - [Developer Advocacy - Sessionize](https://sessionize.com/juarezjunior)
      - [Microsoft TechX - Enterprise Blockchain Application Development using Azure Blockchain Service](https://www.microsoftevents.com/profile/web/index.cfm?PKwebID=0x1462051d571&varPage=agenda)
      - [Microsoft TechX - Highlights by Version 1](https://www.version1.com/nw-cld-maz-highlights-from-microsoft-techx-dublin/)
      - [Microsoft TechX - Event Report by Version 1](https://medium.com/version-1/a-day-at-microsoft-techx-dublin-28a7abb71c9c)
      - [Workshop: Blockchain on Azure for Developers](https://www.microsoftevents.com/profile/form/index.cfm?PKformID=0x9650633abcd)
      - [Hackathon WhatTheHack - Blockchain and The World Food Supply](https://www.slideshare.net/juarezjunior/whatthehack-blockchain-and-the-world-food-supply)
      - [Rio Cloud Conference Day - Blockchain for Java Developers](https://www.youtube.com/watch?v=4Bj4XZqOI0k)
      - [Azure Thursdays - Azure Block Chain Service for Developers](https://www.youtube.com/watch?v=9JsNx_4n11U)    
      - [Limerick .NET Azure Meetup - Microsoft Developers in Ireland](https://twitter.com/ActionPointTech/status/1187425718495567874)         
      - [Cork .NET Azure Meetup - Azure Blockchain Service for Developers](https://www.youtube.com/watch?v=w5744nDwu0E)    
      - [Sec4Dev - Panel: Cloud Security](https://sec4dev.io/sessions/breakout-sessions-secure-sdlc-security-automation-cloud-security)
      - [Azure Blockchain Zürich - Introduction to Blockchain and Blockchain on Azure](https://info.microsoft.com/WE-DevOps-WBNR-FY21-11Nov-20-MicrosoftDevOpsForum-SRDEM47846_LP02OnDemandRegistration-ForminBody.html) 
      - [Azure Blockchain Zürich - CORDA on Azure](https://www.meetup.com/Azure-Blockchain-Zurich/events/rkbkhryzpblc/)           
      - [World Blockchain Conclave - Introduction to Blockchain and Blockchain on Azure](https://1point21gws.com/onlineblockchainsummit/index.php#schedule)
      - [Descomplicando o Azure - Enterprise Blockchain Application Development using the Azure Blockchain Service](https://www.descomplicandoazure.com.br/)      
      - [Microsoft DevOps Forum - DevOps with GitHub](https://info.microsoft.com/WE-DevOps-WBNR-FY21-11Nov-20-MicrosoftDevOpsForum-SRDEM47846_LP02OnDemandRegistration-ForminBody.html)
      - [Pyjamas Conf 2020 - Blockchain for Python Developers](https://www.youtube.com/watch?v=9lMXZALF-iU)
      - [4th Naftemporiki AI Conference 2019 - Panel: Artificial Intelligence vs. Human Prudence](https://www.flickr.com/photos/15201803@N00/albums/72157678467257638)
      - [Shift Conference - Devops with Azure Devops and Github](https://www.slideshare.net/shiftconf/shift-remote-devops-devops-with-azure-devops-and-github-juarez-junior-microsoft)
      - [DUBJUG - The Helidon.io Project - The Collection of Java Libraries for Writing Microservices](https://ti.to/dublin-java-user-group/oracle-blockchain)
      - [DUBJUG - The Oracle Blockchain Cloud Service and Blockchain smart contracts development with Java](https://ti.to/dublin-java-user-group/oracle-blockchain)
      - [Webinars: Transformational Technologies of Today – Blockchain and IoT](https://www.linkedin.com/pulse/transformational-technologies-today-blockchain-iot-juarez-junior/)
      - [JavaRanch Forum](https://coderanch.com/u/27811/Juarez-Alvares-Barbosa-Junior)
          
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
